# Generated by Django 3.2.4 on 2021-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_alter_article_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('about', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
