# Generated by Django 3.2.4 on 2021-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('message_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
