# Generated by Django 3.2.4 on 2021-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='about',
        ),
        migrations.RemoveField(
            model_name='hiring',
            name='birthday',
        ),
        migrations.AddField(
            model_name='hiring',
            name='resumefile',
            field=models.FileField(default=False, upload_to='blogs/documents/'),
        ),
    ]
