# Generated by Django 3.2.5 on 2021-08-09 06:55
# Generated by Django 3.2.5 on 2021-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images/'),
        ),
    ]
