<<<<<<< Updated upstream
# Generated by Django 3.2.5 on 2021-08-09 08:12

import ckeditor_uploader.fields
from django.db import migrations
=======
# Generated by Django 3.2.5 on 2021-08-07 12:28

from django.db import migrations, models
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
<<<<<<< Updated upstream
            field=ckeditor_uploader.fields.RichTextUploadingField(),
=======
            field=models.TextField(max_length=10000),
>>>>>>> Stashed changes
        ),
    ]
